version: '3.8'

services:
    app:
        build: .
        container_name: tasktodo
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        ports:
            - 80:80
        depends_on:
            - db

    db:
        build: ./database
        container_name: mysql
        environment:
            MYSQL_DATABASE: todo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - 3306:3306

networks:
    laravel_network:

volumes:
    mysql-data:
