version: '3.8'

services:
    mysql:
        build: ./database
        ports:
            - "3306:3306"

    php-apache:
        build: .
        ports:
            - "80:80"
        depends_on:
            - mysql
